#include <Test.h>



ON_VALUES_ASSIGNED_IMPLEMENTATION(Test)
{
    m_script = LScript::Script_Stub::construct_from(m_script_stub);
    delete m_script_stub;
    m_script_stub = nullptr;

    m_script->set_context_object("Test", "test", this);
    m_script->set_context_object("Test_2", "test_2", &m_test);
}


SCRIPTABLE_FUNCTIONS_INITIALIZATION_BEGIN(Test)

SCRIPTABLE_FUNCTION_INITIALIZATION_BEGIN;
SCRIPTABLE_FUNCTION_RETURN_TYPE(void);
SCRIPTABLE_FUNCTION_NAME(set_string);
SCRIPTABLE_FUNCTION_ARG(std::string);
SCRIPTABLE_FUNCTION_INITIALIZATION_END;

SCRIPTABLE_FUNCTION_INITIALIZATION_BEGIN;
SCRIPTABLE_FUNCTION_RETURN_TYPE(void);
SCRIPTABLE_FUNCTION_NAME(set_number);
SCRIPTABLE_FUNCTION_ARG(unsigned int);
SCRIPTABLE_FUNCTION_INITIALIZATION_END;

SCRIPTABLE_FUNCTION_INITIALIZATION_BEGIN;
SCRIPTABLE_FUNCTION_RETURN_TYPE(void);
SCRIPTABLE_FUNCTION_NAME(print_data);
SCRIPTABLE_FUNCTION_INITIALIZATION_END;

SCRIPTABLE_FUNCTION_INITIALIZATION_BEGIN;
SCRIPTABLE_FUNCTION_RETURN_TYPE(unsigned int);
SCRIPTABLE_FUNCTION_NAME(number);
SCRIPTABLE_FUNCTION_INITIALIZATION_END;

SCRIPTABLE_FUNCTION_INITIALIZATION_BEGIN;
SCRIPTABLE_FUNCTION_RETURN_TYPE(LDS::Vector<unsigned int>);
SCRIPTABLE_FUNCTION_NAME(numbers);
SCRIPTABLE_FUNCTION_INITIALIZATION_END;

SCRIPTABLE_FUNCTIONS_INITIALIZATION_END;



SCRIPTABLE_FUNCTIONS_INITIALIZATION_BEGIN(Test_2)

SCRIPTABLE_FUNCTION_INITIALIZATION_BEGIN;
SCRIPTABLE_FUNCTION_RETURN_TYPE(void);
SCRIPTABLE_FUNCTION_NAME(print_stuff);
SCRIPTABLE_FUNCTION_INITIALIZATION_END;

SCRIPTABLE_FUNCTIONS_INITIALIZATION_END;
